package com.example.graymatter.domain.business

import com.example.graymatter.domain.ResourceEntryWithDetails
import com.example.graymatter.domain.Opinion
import com.example.graymatter.domain.Resource
import com.example.graymatter.domain.Topic

/**
 * Service to export Relatrix content into Markdown format.
 */
object ExportService {

    fun exportResourceHistory(resourceEntryDetails: ResourceEntryWithDetails, filteredOpinions: List<Opinion>? = null): String {
        val sb = StringBuilder()
        val resource = resourceEntryDetails.resource
        
        sb.append("# Opinion History: ${resource.title ?: "Untitled"}\n\n")
        
        if (resource.url != null) {
            sb.append("**Source:** [${resource.url}](${resource.url})\n\n")
        } else if (resource.filePath != null) {
            sb.append("**Source:** ${resource.filePath.substringAfterLast("/")}\n\n")
        }
        
        if (resourceEntryDetails.resourceEntry.description != null) {
            sb.append("> ${resourceEntryDetails.resourceEntry.description}\n\n")
        }
        
        sb.append("--- \n\n")

        val opinionsToExport = filteredOpinions?.sortedBy { it.createdAt } ?: resourceEntryDetails.opinions.sortedBy { it.createdAt }

        opinionsToExport.forEachIndexed { index, opinion ->
            val pageInfo = if (opinion.pageNumber != null) " (Page ${opinion.pageNumber + 1})" else ""
            sb.append("### ${index + 1}. Reflection$pageInfo\n")
            
            // Format Annotation vs Regular Opinion
            if (opinion.text.startsWith("> ") || opinion.text.startsWith("[INDEX:")) {
                val cleanText = opinion.text.replace(Regex("\\[INDEX:\\d+\\]\\s*"), "")
                sb.append("$cleanText\n\n")
            } else {
                sb.append("${opinion.text}\n\n")
            }
            
            sb.append("**Confidence:** ${opinion.confidenceScore}/100\n\n")
        }
        
        return sb.toString()
    }

    fun exportTopicSummary(topic: Topic, resourceEntriesWithDetails: List<ResourceEntryWithDetails>): String {
        val sb = StringBuilder()
        sb.append("# Topic Analysis: ${topic.name}\n\n")
        
        if (!topic.notes.isNullOrBlank()) {
            sb.append("## Topic Overview\n")
            sb.append("${topic.notes}\n\n")
        }
        
        if (resourceEntriesWithDetails.isNotEmpty()) {
            sb.append("## Resources Included\n\n")
            resourceEntriesWithDetails.forEach { entryDetail ->
                val resource = entryDetail.resource
                val title = resource.title ?: resource.url ?: "Untitled"
                sb.append("### $title\n")
                if (resource.url != null) {
                    sb.append("**Source:** [${resource.url}](${resource.url})\n\n")
                } else if (resource.filePath != null) {
                    sb.append("**Source:** ${resource.filePath.substringAfterLast("/")}\n\n")
                }
                
                if (entryDetail.resourceEntry.description != null) {
                    sb.append("> ${entryDetail.resourceEntry.description}\n\n")
                }
                
                if (entryDetail.opinions.isNotEmpty()) {
                    sb.append("#### Opinion History\n")
                    entryDetail.opinions.sortedBy { it.createdAt }.forEachIndexed { index, opinion ->
                        val pageInfo = if (opinion.pageNumber != null) " (Page ${opinion.pageNumber + 1})" else ""
                        sb.append("${index + 1}. Reflection$pageInfo\n")
                        
                        if (opinion.text.startsWith("> ") || opinion.text.startsWith("[INDEX:")) {
                            val cleanText = opinion.text.replace(Regex("\\[INDEX:\\d+\\]\\s*"), "")
                            sb.append("$cleanText\n\n")
                        } else {
                            sb.append("${opinion.text}\n\n")
                        }
                    }
                } else {
                    sb.append("*No opinions recorded yet.*\n\n")
                }
                sb.append("---\n\n")
            }
        }
        
        sb.append("Generated by Relatrix\n")
        
        return sb.toString()
    }
}
