package com.example.graymatter.domain.business

import com.example.graymatter.domain.ItemWithDetails
import com.example.graymatter.domain.Opinion
import com.example.graymatter.domain.Resource
import com.example.graymatter.domain.Topic

/**
 * Service to export Gray Matter content into Markdown format.
 */
object ExportService {

    fun exportItemHistory(itemDetails: ItemWithDetails, filteredOpinions: List<Opinion>? = null): String {
        val sb = StringBuilder()
        val resource = itemDetails.resource
        
        sb.append("# Opinion History: ${resource.title ?: "Untitled"}\n\n")
        
        if (resource.url != null) {
            sb.append("**Source:** [${resource.url}](${resource.url})\n\n")
        } else if (resource.filePath != null) {
            sb.append("**Source:** ${resource.filePath.substringAfterLast("/")}\n\n")
        }
        
        if (itemDetails.item.description != null) {
            sb.append("> ${itemDetails.item.description}\n\n")
        }
        
        sb.append("--- \n\n")

        val opinionsToExport = filteredOpinions?.sortedBy { it.createdAt } ?: itemDetails.opinions.sortedBy { it.createdAt }

        opinionsToExport.forEachIndexed { index, opinion ->
            val pageInfo = if (opinion.pageNumber != null) " (Page ${opinion.pageNumber + 1})" else ""
            sb.append("### ${index + 1}. Reflection$pageInfo\n")
            
            // Format Annotation vs Regular Opinion
            if (opinion.text.startsWith("> ")) {
                sb.append("${opinion.text}\n\n")
            } else {
                sb.append("${opinion.text}\n\n")
            }
            
            sb.append("**Confidence:** ${opinion.confidenceScore}/100\n\n")
        }
        
        return sb.toString()
    }

    fun exportTopicSummary(topic: Topic, itemsWithDetails: List<ItemWithDetails>): String {
        val sb = StringBuilder()
        sb.append("# Topic Analysis: ${topic.name}\n\n")
        
        if (!topic.notes.isNullOrBlank()) {
            sb.append("## Overall Opinion\n")
            sb.append("${topic.notes}\n\n")
        }
        
        if (itemsWithDetails.isNotEmpty()) {
            sb.append("## Resources Included\n\n")
            itemsWithDetails.forEach { itemDetail ->
                val resource = itemDetail.resource
                val title = resource.title ?: resource.url ?: "Untitled"
                sb.append("### $title\n")
                if (resource.url != null) {
                    sb.append("**Source:** [${resource.url}](${resource.url})\n\n")
                } else if (resource.filePath != null) {
                    sb.append("**Source:** ${resource.filePath.substringAfterLast("/")}\n\n")
                }
                
                if (itemDetail.item.description != null) {
                    sb.append("> ${itemDetail.item.description}\n\n")
                }
                
                if (itemDetail.opinions.isNotEmpty()) {
                    sb.append("#### Opinion History\n")
                    itemDetail.opinions.sortedBy { it.createdAt }.forEachIndexed { index, opinion ->
                        val pageInfo = if (opinion.pageNumber != null) " (Page ${opinion.pageNumber + 1})" else ""
                        sb.append("${index + 1}. Reflection$pageInfo\n")
                        
                        if (opinion.text.startsWith("> ")) {
                            sb.append("${opinion.text}\n\n")
                        } else {
                            sb.append("${opinion.text}\n\n")
                        }
                    }
                } else {
                    sb.append("*No opinions recorded yet.*\n\n")
                }
                sb.append("---\n\n")
            }
        }
        
        sb.append("Generated by Gray Matter\n")
        
        return sb.toString()
    }
}
